objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audit_Date_Same__c</fullName>
        <formula>IF (Mozilla_Verified_Audit_Date__c = Standard_Audit_Statement_Date__c, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Set field to false &apos;Mozilla Verified Audit Date&apos; is not the same as the &apos;Standard Audit Statement Date&apos;</inlineHelpText>
        <label>Audit Date Same?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <description>This field is hyperlink to Account Name. Mainly used in reports.</description>
        <formula>HYPERLINK(Id, Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certificate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_of_Revocation__c</fullName>
        <label>Date of Revocation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mozilla_Verified_Audit_Date__c</fullName>
        <label>Mozilla Verified Audit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OneCRL_Status__c</fullName>
        <label>OneCRL Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Add</fullName>
                </value>
                <value>
                    <fullName>Added to OneCRL</fullName>
                </value>
                <value>
                    <fullName>Cert Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC_5280_Revocation_Reason_Code__c</fullName>
        <inlineHelpText>Provide the reason for the certificate revocation. Value 7 is not being used.</inlineHelpText>
        <label>RFC 5280 Revocation Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(0) unspecified</fullName>
                </value>
                <value>
                    <fullName>(1) keyCompromise</fullName>
                </value>
                <value>
                    <fullName>(2) cACompromise</fullName>
                </value>
                <value>
                    <fullName>(3) affiliationChanged</fullName>
                </value>
                <value>
                    <fullName>(4) superseded</fullName>
                </value>
                <value>
                    <fullName>(5) cessationOfOperation</fullName>
                </value>
                <value>
                    <fullName>(6) certificateHold</fullName>
                </value>
                <value>
                    <fullName>(8) removeFromCRL</fullName>
                </value>
                <value>
                    <fullName>(9) privilegeWithdrawn</fullName>
                </value>
                <value>
                    <fullName>(10) aACompromise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removal_Bug_No_or_Date__c</fullName>
        <label>Mozilla Removal Bug No. or Date</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sponsored_By__c</fullName>
        <label>Sponsored By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Microsoft</fullName>
                </value>
                <value>
                    <fullName>Mozilla</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Summary__c</fullName>
        <formula>&quot;Mozilla: &quot; + Text(Status__c) + &quot;; Microsoft: &quot; + Text(Microsoft_Status__c) 

/* &quot;Mozilla: &quot; + Text(Status__c) + &quot;; Microsoft: &quot; + Text(Microsoft_Status__c) + &quot;; Cisco: &quot; + Text(Cisco_Status__c) + &quot;; Google: &quot; + Text(Google_Status__c)*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Public comments</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Latest_Case_Comment__c</fullName>
        <description>Update by workflow and field update</description>
        <label>Latest Case Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Summary__c</fullName>
        <formula>&quot;Mozilla = &quot; + Text(Request_Status__c) + &quot;; Microsoft = &quot; + Text(Microsoft_Request_Status__c) + &quot;;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Request Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <defaultValue>&quot;NEED CRL URLs and CRL issuing frequency for subscriber certs, with reference to where this is documented in the CP/CPS&quot;</defaultValue>
        <label>DELETE CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <label>DELETE Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Summary__c</fullName>
        <formula>&quot;Mozilla = &quot; + Text(Request_Status__c) + &quot;; Microsoft = &quot; + Text(Microsoft_Request_Status__c) + &quot;;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Request Status</label>
        <type>Text</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RSHomePageController.cls
/*******************************************************************************************************
 Name: RSHomePageController

 Dependencies: RSHomePageController controller class, RSHomePage vf page, RSHomePageControllerTest test class

 Description: This is Mozilla's Root Store's Task List report (added to home page). It generates
 various reports wih record count. Detail report is only displayed when the 
 record count is greater than 1.
    
    Report sections showing the following ...
    
    1) Open Leads 
    2) Open Audit Cases assigned to Mozilla which are updated by CA 
    3) Open Root Inclusion Cases which are updated by CA 
    4) Audit Data Integrity (which linked to vf page)
    5) Verify Updated Audits
    6) Verify Revoked Certst  
    7) Externally Operated Intermediate Certs missing Owner or Auditor Info
    8) Expired Root Certificates
    
 Instructions: Add the VF page to Root Store's home page
 *******************************************************************************************************
 Revision History:
 
     7/2/2019 - Created new class.
     7/12/2019 - Adding new section Externally Operated Intermediate Certs missing Owner or Auditor Info.
     8/5/2019  - Added custom sort for CRL URL column and other minor additions.
     8/13/2019 - Updated Where condition for Externally Intermediate certs Missing Info.
     8/29/2019 - Added filter for "Denied" records; IsConverted check was not sufficient.
     9/10/2019 - Found that using wrong status 'Changed Requested', so updated to 'Change Requested'
     9/23/2019 - Added a new section 'CAs Missing Emails'
 ******************************************************************************************************/
 
public with sharing class RSHomePageController {
    
    public List<Lead> lstOpenLeads {get; set;}
    public List<Case> lstAuditCases {get; set;}
    public List<Case> lstInclusionCases {get; set;}   
    public List<Account> lstVerifyUpdatedAudits {get; set;}
    public List<Account> lstVerifyRevokedCerts {get; set;}
    public List<Account> lstIntermediateCertsMissingInfo {get; set;}
    public List<Account> lstExpiredRootCertificates {get; set;}
    public List<Account> lstCAsMissingEmails {get; set;}
    
    public RSHomePageController(){
    
        lstOpenLeads = new List<Lead>([select Id, Name, Website, Company, Organization_Type__c, CP_CPS_document_URLs__c, Sponsored_By__c 
                                       from Lead where Status != 'Denied' and IsConverted = false Order by Sponsored_By__c desc]);

        List<User> lstCAUsers = new List<User>([select Id from User Where ContactID != null]);
        
        /* lstAuditCases = new List<Case>([select ID,CaseNumber,AccountId, Account.Name,Status_Summary__c,Request_Status__c,
                        Case_Assigned_To__c,Case_Assigned_To__r.Name, LastModifiedDate, LastModifiedById, LastModifiedBy.Name
                        from Case Where RecordType.Name = 'CA Audit Update Request' AND LastModifiedById =: lstCAUsers
                        AND LastModifiedDate = LAST_N_DAYS:30 and Request_Status__c != 'Complete' Order by CaseNumber,AccountId]); */
        
        /*set<Id> setofCaseIds = new set<ID>();
        for(Root_Case__c rootcase: [Select Case_No__c from Root_Case__c Where Case_No__r.Case_Assigned_To__r.Name = 'Kathleen Wilson']){
            setofCaseIds.add(rootcase.Case_No__c);
        }  */            
        lstAuditCases = new List<Case>([select ID, CaseNumber, AccountId, Account.Name, Request_Status__c,Latest_Case_Comment__c,
                        Case_Assigned_To__c, Case_Assigned_To__r.Name, Subject, LastModifiedDate, LastModifiedById, LastModifiedBy.Name
                        From Case Where RecordType.Name = 'CA Audit Update Request' AND Request_Status__c != 'Complete'
                        And Case_Assigned_To__r.Name = 'Kathleen Wilson'
                        Order by LastModifiedDate]); 
        
        set<string> setOfRequestStatuses = new set<string>();
        setOfRequestStatuses.add('Initial Request Received');
        setOfRequestStatuses.add('Information Verification in Process');
        setOfRequestStatuses.add('In Detailed CP/CPS Review');
        setOfRequestStatuses.add('In Public Discussion');
        setOfRequestStatuses.add('Pending Approval');
        setOfRequestStatuses.add('Approved, Pending Inclusion');
        setOfRequestStatuses.add('Approved, Pending Inclusion and EV');
        setOfRequestStatuses.add('Included, Pending EV');                         
        lstInclusionCases = new List<Case>([select ID,CaseNumber,AccountId, Account.Name,Status_Summary__c,Request_Status__c,
                        Case_Assigned_To__c,Case_Assigned_To__r.Name, Subject, LastModifiedDate, LastModifiedById, LastModifiedBy.Name
                        From Case Where RecordType.Name = 'CA Root Inclusion Request' AND Request_Status__c =: setOfRequestStatuses 
                        Order by Request_Status__c, LastModifiedDate]);
        
        lstVerifyUpdatedAudits = new List<Account>([select Id,Name,Standard_Audit_Statement_Date__c,Mozilla_Verified_Audit_Date__c,
                        Removal_Bug_No_or_Date__c, Comments__c, LastModifiedDate, LastModifiedBy.Name                      
                        From Account 
                        Where RecordType.Name = 'Root Certificate' 
                        AND Status__c in ('Included','Change Requested') 
                        AND Audit_Date_Same__c = false
                        Order by Name]);
        
        //verify revoked certs.
        List<wrapperRevokedCerts> lstWrapperRevokedCerts = new List<wrapperRevokedCerts>();
        List<Account> lstVerifyRevokedCertsTemp = new List<Account>([select Id,Name,ParentId,Parent.Name,Certificate_Name__c,Valid_From_GMT__c,
                        Valid_To_GMT__c,Comments__c,CRL_URL_s__c,Certificate_Serial_Number__c,SHA_256_Fingerprint__c,
                        OneCRL_Status__c,Date_of_Revocation__c,RFC_5280_Revocation_Reason_Code__c from Account Where 
                        RecordType.Name = 'Intermediate Certificate' AND 
                        Revocation_Status__c = 'Revoked' AND OneCRL_Status__c not in ('Ready to Add','Added to OneCRL','Cert Expired') 
                        AND CA_Owner_Mozilla_Status__c in ('Included','Change Requested')
                        Order by Name]);
        for(Account objAcc: lstVerifyRevokedCertsTemp){
            lstWrapperRevokedCerts.add(new wrapperRevokedCerts(objAcc.CRL_URL_s__c, objAcc));
        }
        lstWrapperRevokedCerts.sort();
        lstVerifyRevokedCerts = new List<Account>();
        for(wrapperRevokedCerts revoked: lstWrapperRevokedCerts){
            lstVerifyRevokedCerts.add(revoked.objAcc);
        }
        
        lstIntermediateCertsMissingInfo = new List<Account>([select Id,Name,CA_Owner__c,Certificate_Name__c,Valid_From_GMT__c,Revocation_Status__c ,
                        Valid_To_GMT__c,Subordinate_CA_Owner__c,Auditor_New__c,Auditor_New__r.Name,Audits_Same_as_Parent__c from Account Where 
                        RecordType.Name = 'Intermediate Certificate' 
                        AND Revocation_Status__c = 'Not Revoked' 
                        AND OneCRL_Status__c != 'Added to OneCRL'
                        AND Valid_To_GMT__c > TODAY 
                        AND Audits_Same_as_Parent__c = FALSE 
                        AND (Subordinate_CA_Owner__c = null OR Auditor_New__c = null)
                        AND Root_Cert_Id__r.Status__c In ('Included','Change Requested') 
                        AND Technically_Constrained__c = FALSE
                        Order by Name,CA_Owner__c]);
        
        lstExpiredRootCertificates = new List<Account>([select Id,Name,ParentId, Parent.Name, Valid_From_GMT__c, Valid_To_GMT__c, 
                        Trust_Bits__c, Removal_Bug_No_or_Date__c from Account WHERE RecordType.Name = 'Root Certificate' 
                        AND Status__c in ('Included','Change Requested') 
                        AND Valid_To_GMT__c < TODAY Order by Parent.Name,Name]);
                        
        lstCAsMissingEmails = new List<Account>([select Id,Name,Status__c from Account Where RecordType.Name = 'CA Owner'
                        AND Status__c in ('Included','Change Requested') AND CA_Email_Alias_1__c = null AND CA_Email_Alias_2__c = null
                        Order by Name]);
    }
    
    //wrapper class for Revoked Certs to Sort by CRLURL long text area field.
    public class wrapperRevokedCerts implements Comparable {
        public string CRLURL;
        public Account objAcc;
        public wrapperRevokedCerts (string crl, Account acc){
            this.CRLURL = crl != null ? crl : '';
            this.objAcc = acc;
        }
        public Integer compareTo(Object obj) {
            wrapperRevokedCerts revokedCert = (wrapperRevokedCerts)(obj);
            if (this.CRLURL > revokedCert.CRLURL) {
                return 1;
            }
            if (this.CRLURL == revokedCert.CRLURL) {
                return 0;
            }

            return -1;
        }
    }
}