objects/Account.object
<CustomObject>
    <fields>
        <fullName>Issuer__c</fullName>
        <inlineHelpText>Certificate Issuer Common Name + Certificate Issuer Organizational Unit + Certificate Issuer Organization + Certificate Issuer Country</inlineHelpText>
        <label>Issuer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Cert_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by PublicAllIntermediateCerts batch program for all intermediate cert records.</inlineHelpText>
        <label>Root Cert Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root_Status__c</fullName>
        <formula>TEXT( Root_Cert_Id__r.Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This formula field derives root status from &apos;Root Cert Id&apos; field. &apos;Root Cert Id&apos; is populated for all intermediate certs by PublicAllIntermediateCerts batch program.</inlineHelpText>
        <label>Root Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MozillaIntermediateCertsReportController.cls
public class MozillaIntermediateCertsReportController {

    public List<Account> lstIntermediateCerts {get;set;}
 
    //constructor method for standard controller
    public MozillaIntermediateCertsReportController() {   
          
        lstIntermediateCerts =  [select Id, Name, Subject__c, Issuer__c, SHA_256_Fingerprint__c, X_509_Certificate_PEM__c from Account
                                      where Name != '<Fill in Cert Name>' and RecordType.Name = 'Intermediate Certificate' and  
                                      Revocation_Status__c not in ('Revoked','Parent Cert Revoked') and 
                                      Root_Status__c in ('Included','Change Requested') and Valid_To_GMT__c > TODAY and
                                      Root_Cert_Id__r.Trust_Bits__c includes ('Websites')
                                      order by Name];
                                          
                                          
                                          
        // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        if((Test.IsRunningTest() || ApexPages.currentPage().getUrl().contains('CSV')) && lstIntermediateCerts !=null && lstIntermediateCerts.size() > 0)
        {
            for(Account acc: lstIntermediateCerts){
                if(acc.name !=null && acc.name.length() > 0) 
                    acc.name = acc.name.replace('"',''); 
                if(acc.Subject__c !=null && acc.Subject__c.length() > 0) 
                    acc.Subject__c = acc.Subject__c.replace('"','');
                if(acc.Issuer__c !=null && acc.Issuer__c.length() > 0) 
                    acc.Issuer__c = acc.Issuer__c.replace('"','');
                if(acc.SHA_256_Fingerprint__c !=null && acc.SHA_256_Fingerprint__c.length() > 0) 
                    acc.SHA_256_Fingerprint__c = acc.SHA_256_Fingerprint__c.replace('"','').replace(':','');
            }
        }
    }
}